export const USER_LOGIN_REQUEST = 'USERR_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USERR_LOGIN_SUCCESs';
export const USER_LOGIN_FAIL = 'USERR_LOGIN_FAIL';
export const USER_LOGOUT = 'USERR_LOGOUT';
